CREATE TABLE IF NOT EXISTS cerstable (
    day INT PRIMARY KEY NOT NULL,
    purpose VARCHAR(50) NOT NULL,
    car VARCHAR(255) NOT NULL NOT NULL,
    driver VARCHAR(50) NOT NULL,
    destination VARCHAR(255) NOT NULL,
    department VARCHAR(225) NOT NULL
);
