CREATE TABLE IF NOT EXISTS cerstable (
    day INT PRIMARY KEY AUTO_INCREMENT,
    purpose NOT NULL DEFAULT CURRENT_TIMESTAMP,
    car VARCHAR(255) NOT NULL UNIQUE KEY,
    driver VARCHAR(50) NOT NULL,
    destination VARCHAR(255) NOT NULL,
    department NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
